baseURL = "venqiu.github.io/repopres"
languageCode = 'en-us'
title = 'Netizen of Guide to Preserving Github Repositories'
theme = "hugo-book"

enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookTheme = 'auto'      
  BookToC = true         
  BookSection = 'docs'   
